name: 'Update issues'
description: 'Update issues with tasks'
inputs:
  repo-token:  # id of input
    description: 'Github actions repo token'
    required: true
  workflow-action:
    description: 'Subcommand for the action'
    required: true
  issuenumber:
    description: 'Number of issue that is to be updated'
    required: false

runs:
  using: 'node20'
  main: 'index.js'

