name: 'Hello World'
description: 'Test reading file'
inputs:
  repo-token:  # id of input
    description: 'Github actions repo token'
    required: true
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'

