run-name: Updating and labeling all issues
on:
    workflow_dispatch:
env:
  GITHUB_REPO_NAME: instruments
jobs:
    run-updated-reopen:
        runs-on: ubuntu-latest
        name: Update and label issue job
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run issues step
              uses: ./.github/actions/
              with:
                  workflow-action: update-labels
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
